linn/react-components-library

- package-lock.json
- package.json
- src/components/TypeaheadDialog.js
clear search term after search and add tooltip to TypeaheadDialog
> Typeahead changes

- index.js
- package-lock.json
- package.json
> add error details message selector to index

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/components/ValidatedInputDialog.js
- src/stories/EntityList.stories.js
- src/stories/Page.stories.js
- src/stories/ReportTable.stories.js
- src/stories/TypeaheadDialog.stories.js
- src/stories/ValidatedInputDialog.stories.js
- src/stories/renderUtils/Providers.js
- new component... similar to the TypeaheadDialog except instead of showing search results this components just gives feedback as to whether the thing under search exists or not. For example as an 'Enter Works Order' Dialog the component will go red and not allow you to accept if you enter an invalid worksOrderNumber or Green and allow you to acceptif you enter a valid one. I think this'll come in quite handy but can demo it at show n tell if there are doubts.
- also fixed various story issues introduced by notistack and themes - defining a common provider function that wraps stories in all the gubbings they need to not error
> Validated input dialog

- CHANGELOG.md
- package.json
- src/actions/makeProcessActionTypes.js
> add missing action type

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/components/LinnWeekPicker.js
- src/stories/LinnWeekPicker.stories.js
Still haven't figured out how to test this without the testing library crashing...
> LinnWeekPicker component

- CHANGELOG.md
- package-lock.json
- package.json
- this pr fixes stuff that updating the template broke. It'll be a breaking change so I'll up the version to 10 and write a changelog before merging
> Peer dependencies

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Page.js
material UI grid is doing
.MuiGrid-spacing-xs-3 {
width: calc(100% + 24px);
margin: -12px;
}
But it doesn't work out properly for us for some reason, it would need to be -24px. This fixes it just by setting the width for this to 100% but unsure if this is the right fix or not, up for debate
#106
> Get rid of side scrolling

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Navigation.js
broke stuff by trying to put classes.root and my printing class on the same div, just unbreaking it
> tiny printing class change

- CHANGELOG.md
- package.json
- src/components/BackButton.js
- src/components/TypeaheadTable.js
- src/components/__tests__/BackButton.test.js
- src/hooks/useSearch.js
> Alternative back button text

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/ReportTable.js
client side extensions to allow report table column widths to be set to fixed sizes small/medium/large
A server side solution may follow
> Tablewidth

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/MultiReportTable.js
- src/components/ReportTable.js
report table and multi report table. For liz for most recent reply to ticket http://rndsupport.linn.co.uk/scp/tickets.php?id=12113
> made report table avoid page break style optional 

- package-lock.json
- package.json
- src/components/DatePicker.js
- src/components/__tests__/LinnWeekPicker.test.js
- the new major version upgrade for moment breaks @material-ui/pickers https://github.com/mui-org/material-ui-pickers/issues/1440 
- Just reverting for now. We could switch to a different date library if they don't sort this soon but I remember @atcampbell having a bit of a hard time doing this before (some WeekPicker complications come to mind?)
> revert moment

- CHANGELOG.md
- package.json
- src/actions/UpdateApiActions.js
- src/components/__tests__/EditableTableRow.test.js
- src/components/editableTable/EditableTable.js
- src/components/editableTable/EditableTableRow.js
- src/components/editableTable/componentFactory.js
- EditableTable
- Delete row functionality
- Optional custom update row function
- Optional validate row function
- Fields that are required but not editable can now be changed when creating a new row and will be read only when editing
- Update styling of Save, Cancel and Delete buttons on table rows
- UpdateApiActions.delete - id can be null
> Editable table updates

- CHANGELOG.md
- package.json
- src/components/editableTable/EditableTable.js
- src/components/editableTable/EditableTableRow.js
change EditableTable to have option of disallowing row creation.
change EditableTableRow to not show edit button when not editable.
> Editable Table tweaks

- CHANGELOG.md
- package-lock.json
- package.json
- src/styles/printStyles.css
Also added the smaller and more to the right date from Richard's pr
> Try adding optional class to print landscape

- CHANGELOG.md
- package.json
- src/components/Typeahead.js
- src/stories/Typeahead.stories.js
Allows for a field to either be typed or populated from the search depending on the expertise of the user.
> Add searchButtonOnly option to modal mode. 

- CHANGELOG.md
- package.json
- src/components/Breadcrumbs.js
- src/components/Page.js
- optionally specify what happens when the user clicks the home crumb. Defaults to app.linn.co.uk but you can set it to be anything you like, e.g. appRoot
> breadcrumbs home url

- CHANGELOG.md
- package.json
- src/components/SearchIcon.js
- src/components/Typeahead.js
- src/components/__tests__/Typeahead.test.js
> Optional typeaheads

- CHANGELOG.md
- index.js
- src/selectors/__tests__/userSelectors.js
- src/selectors/reportSelectorHelpers.js
- src/selectors/userSelectors.js
The old getUserName method used in previous solutions is still there so not breaking change
> combine userSelectors for consistency

- CHANGELOG.md
- package-lock.json
- package.json
- src/actions/UpdateApiActions.js
- src/actions/makeActionTypes.js
- src/actions/rsaaTypes.js
- src/reducers/__tests__/itemStoreFactory.js
- src/reducers/reducerFactories/itemStoreFactory.js
as discussed turns out I do want to use this in my own form now
> Post by href attempt #2

- CHANGELOG.md
- package-lock.json
- package.json
- src/actions/UpdateApiActions.js
- src/actions/makeActionTypes.js
- src/actions/rsaaTypes.js
- src/reducers/__tests__/itemStoreFactory.js
- src/reducers/reducerFactories/itemStoreFactory.js
adding PATCH actions, will add this to the OB module.
> Add PATCH to Components Library

- CHANGELOG.md
- package.json
- src/components/ExportButton.js
- adds indications of a loading state and fail state
> Better export button

- .eslintrc.json
- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- rollup.config.js
- src/components/AddressUtility.js
- src/components/__tests__/AddressUtility.test.js
- src/stories/AddressUtility.stories.js
- src/stories/AddressUtilityDocs.mdx
- src/test-utils.js
- I decided not to include my new Search in this PR. I'm going to incubate it in purchasing for a bit to see how users get on with it before I commit it to common code
> Search and address ut components

- .eslintrc.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Search.js
- src/components/__tests__/Search.test.js
- src/stories/Search.stories.js
- src/stories/SearchDocs.mdx
for adding things like 'closed' tags to accounts, etc
> add optional search result chips

- CHANGELOG.md
- index.js
- package.json
- rollup.config.js
- src/components/AddressUtility.js
- src/components/InputField.js
- src/components/Search.js
- src/components/__tests__/AddressUtility.test.js
- src/containers/AddressUtilityReduxContainer.js
- src/stories/AddressUtility.stories.js
- src/stories/AddressUtilityDocs.mdx
- from sales.sln, but want to reuse in purchasing so sticking it in the comp lib
> New address utility bits

- CHANGELOG.md
- package.json
- src/components/AddressUtility.js
- src/containers/AddressUtilityReduxContainer.js
- src/stories/AddressUtility.stories.js
- src/stories/AddressUtilityDocs.mdx
> Experiemnt to try fix obscure bug
